### PR TITLE
Add __nirum_annotations__ on record type

### PR DESCRIPTION
**Pull request by AlanSynn**
Add `__nirum_annotations__` on record type.

### CODE REVIEW

**Comment by admire93** [comment]
@AlanSynn I think we missed that tracking an `annotation-test-record` in `test/nirum_fixture/fixture/foo.nrm` file. Could you add it on this PR?

**Comment by AlanSynn** [comment]
@admire93 Oops... My apologies. I'll add it in the morning. 
(Cause I'm on my way to setting my mac for daily uses, Sorry!)

**Comment by admire93** [comment]
@AlanSynn It's fine :) Thanks to your contribution!! Have a nice day.

**Comment by AlanSynn** [comment]
@admire93 Yeah I got that one too. I've already rebased my branch. Thanks!

**Pull request closed without merging**
